'use client'

import Link from 'next/link'
import { ArrowLeft, ArrowRight } from 'lucide-react'
import { useEffect, useState } from 'react'
import { signOut, User } from 'firebase/auth'
import { collection, getDocs, query, where } from 'firebase/firestore'
import { auth, db } from '@/lib/firebase'

type Order = { id: string; displayOrderId?: string; totalAmount?: number; orderStatus?: string }
export default function AccountPage() { const [user, setUser] = useState<User | null>(null); const [name, setName] = useState(''); const [orders, setOrders] = useState<Order[]>([]); useEffect(() => { if (!auth) return; return auth.onAuthStateChanged(async current => { setUser(current); if (current) { const profile = await (await import('firebase/firestore')).getDoc((await import('firebase/firestore')).doc(db, 'customers', current.uid)); setName(String(profile.data()?.name || current.email || 'Customer')); const snapshot = await getDocs(query(collection(db, 'orders'), where('customerId', '==', current.uid))); setOrders(snapshot.docs.map(item => ({ id: item.id, ...(item.data() as Omit<Order, 'id'>) }))) } }) }, []); if (!user) return <main className="order-page"><section className="order-card"><h1>Sign in to view your account.</h1><Link className="button button-dark" href="/account/login">SIGN IN <ArrowRight size={15} /></Link></section></main>; const recent = orders[0]; return <main className="order-page"><header className="detail-header"><Link href="/" className="back-link"><ArrowLeft size={16} /> STORE</Link><span className="logo">MY ACCOUNT</span><button className="button button-dark" onClick={() => signOut(auth)}>LOG OUT</button></header><section className="account-content"><p className="eyebrow">ACCOUNT</p><h1>Hello, {name}</h1><div className="account-actions"><Link className="button button-dark" href="/orders">MY ORDERS</Link><Link className="button button-outline" href="/account/profile">PROFILE & SAVED ADDRESS</Link></div>{recent && <div className="recent-order"><p className="eyebrow">RECENT ORDER</p><b>#{recent.displayOrderId || recent.id}</b><strong>₹{Number(recent.totalAmount || 0).toLocaleString('en-IN')}</strong><em>{recent.orderStatus || 'NEW'}</em><Link href={`/orders/${recent.id}`}>TRACK ORDER <ArrowRight size={15} /></Link></div>}</section></main> }
