'use client'

import { FormEvent, useEffect, useMemo, useState } from 'react'
import { ArrowLeft, ArrowRight, MessageCircle } from 'lucide-react'
import Link from 'next/link'
import { calculateDelivery, defaultDeliverySettings, defaultServiceArea, getBulkOrderUrl, isServiceableLocation } from '@/lib/commerce'
import { products } from '@/lib/products'
import { addDoc, collection, serverTimestamp } from 'firebase/firestore'
import { auth, db } from '@/lib/firebase'

type CartLine = { productId: string; name: string; image: string; color: string; size: string; quantity: number; price: number; sku: string }
type SavedCartItem = Partial<CartLine> & { id?: string }
const money = (value: number) => `₹${value.toLocaleString('en-IN')}`

export default function CheckoutPage() {
  const [lines] = useState<CartLine[]>(() => { if (typeof window === 'undefined') return []; const saved = JSON.parse(localStorage.getItem('lattey-wallah-cart') || '[]') as SavedCartItem[]; return saved.map(item => item.productId ? item as CartLine : { productId: item.id || '', name: item.name || '', image: item.image || '', color: item.color || '', size: 'M', quantity: 1, price: item.price || 0, sku: item.id || '' }) })
  const [form, setForm] = useState({ name: '', phone: '', email: '', address: '', city: '', state: 'Delhi', pincode: '', requirement: '' })
  const [outside, setOutside] = useState(false)
  const [userReady, setUserReady] = useState(false)
  const [userId, setUserId] = useState('')
  useEffect(() => { if (!auth) { setUserReady(true); return }; return auth.onAuthStateChanged(user => { setUserReady(true); setUserId(user?.uid || '') }) }, [])
  const subtotal = useMemo(() => lines.reduce((total, line) => total + line.price * line.quantity, 0), [lines])
  const settings = typeof window !== 'undefined' ? JSON.parse(localStorage.getItem('lattey-wallah-delivery-settings') || JSON.stringify(defaultDeliverySettings)) : defaultDeliverySettings
  const serviceArea = typeof window !== 'undefined' ? JSON.parse(localStorage.getItem('lattey-wallah-service-area') || JSON.stringify(defaultServiceArea)) : defaultServiceArea
  const delivery = calculateDelivery(subtotal, settings)
  const total = subtotal + delivery
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!userReady || !userId) { window.location.href = '/account/login'; return } if (!isServiceableLocation(form.city, form.pincode, serviceArea)) { setOutside(true); return } const order = { customerId: userId, customer: { name: form.name, email: form.email, phone: form.phone }, items: lines, deliveryAddress: { address: form.address, city: form.city, state: form.state, pincode: form.pincode }, subtotal, deliveryCharge: delivery, totalAmount: total, paymentMethod: 'UPI', paymentStatus: 'PENDING', orderStatus: 'PENDING PAYMENT', createdAt: serverTimestamp(), updatedAt: serverTimestamp() }; const created = await addDoc(collection(db, 'orders'), order); window.location.href = `/orders/${created.id}` }
  const bulkUrl = getBulkOrderUrl(process.env.NEXT_PUBLIC_WHATSAPP_NUMBER || '919999999999', { name: form.name, phone: form.phone, location: `${form.city}, ${form.state}, ${form.pincode}`, requirement: form.requirement || 'Please share available products and delivery options.' })
  return <main className="checkout-page"><header className="detail-header"><Link href="/#shop" className="back-link"><ArrowLeft size={16} /> CONTINUE SHOPPING</Link><Link href="/" className="logo">LATTEY <span>WALLAH</span></Link><span className="eyebrow">CHECKOUT</span></header><div className="checkout-grid"><section><p className="eyebrow">DELIVERY DETAILS</p><h1>Where should we send it?</h1><form className="checkout-form" onSubmit={submit}><label>Full name<input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></label><label>Mobile number<input required pattern="[0-9]{10}" value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })} /></label><label>Email<input required type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} /></label><label className="wide">Full address<textarea required value={form.address} onChange={e => setForm({ ...form, address: e.target.value })} /></label><label>City<input required placeholder="Delhi / Noida / Gurugram" value={form.city} onChange={e => setForm({ ...form, city: e.target.value })} /></label><label>State<input required value={form.state} onChange={e => setForm({ ...form, state: e.target.value })} /></label><label>Pincode<input required pattern="[0-9]{6}" value={form.pincode} onChange={e => setForm({ ...form, pincode: e.target.value })} /></label><button className="button button-dark wide checkout-button" type="submit">CHECK SERVICEABILITY & CONTINUE <ArrowRight size={16} /></button></form><p className="bulk-link" onClick={() => setOutside(true)}>Bulk Order / Outside NCR? <span>Talk to us on WhatsApp →</span></p></section><aside className="summary"><p className="eyebrow">ORDER SUMMARY</p>{lines.length ? lines.map((line, index) => <div className="summary-line" key={`${line.productId}-${index}`}><img src={line.image} alt="" /><div><b>{line.name}</b><span>{line.color} · {line.size} · Qty {line.quantity}</span></div><strong>{money(line.price * line.quantity)}</strong></div>) : <p>Your bag is empty. <Link href="/#shop">Shop now</Link></p>}<div className="summary-total"><p><span>Subtotal</span><b>{money(subtotal)}</b></p><p><span>Delivery</span><b>{delivery ? money(delivery) : 'FREE'}</b></p><p className="grand"><span>Total</span><b>{money(total)}</b></p></div><small>Free delivery on orders above {money(settings.freeDeliveryThreshold)}.</small></aside></div>{outside && <div className="modal-backdrop"><div className="service-modal"><button className="modal-close" onClick={() => setOutside(false)}>×</button><p className="eyebrow">DELIVERY AREA</p><h2>Sorry, we currently deliver only within Delhi NCR.</h2><p>Need a bulk order or delivery outside our service area? Send us a WhatsApp enquiry and we’ll help personally.</p><a className="button whatsapp full" href={bulkUrl} target="_blank" rel="noreferrer"><MessageCircle size={17} /> BULK ORDER / CONTACT US</a></div></div>}</main>
}
