'use client'

import Link from 'next/link'
import { ArrowLeft, ArrowRight, Minus, Plus, ShoppingBag, MessageCircle } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { watchCatalog } from '@/lib/firestore-catalog'
import { Product, ProductVariant } from '@/lib/products'
import { addCartLine, readCart, writeCart, CartLine } from '@/lib/cart'

const money = (value: number) => `₹${value.toLocaleString('en-IN')}`
export default function ProductPage({ params }: { params: { id: string } }) {
  const [productData, setProduct] = useState<Product | null>(null); const [loading, setLoading] = useState(true); const [imageIndex, setImageIndex] = useState(0); const [color, setColor] = useState(''); const [size, setSize] = useState(''); const [quantity, setQuantity] = useState(1)
  useEffect(() => watchCatalog(catalog => { setProduct(catalog.find(item => item.id === params.id) || null); setLoading(false) }, () => undefined, () => setLoading(false)), [params.id])
  const whatsappText = useMemo(() => productData ? `Hello lattey wala,\n\nI want to order:\n${productData.name}\nSize: ${size || 'Not selected'}\nColor: ${color || productData.color}\nQuantity: ${quantity}\nPrice: ${money(productData.price)}` : '', [productData, size, color, quantity])
  if (loading) return <main className="detail-page"><div className="empty-search"><h3>Loading product…</h3></div></main>
  if (!productData) return <main className="detail-page"><div className="empty-search"><h3>Product not found</h3><Link href="/#shop" className="button button-dark">BACK TO SHOP</Link></div></main>
  const product = productData; const gallery = product.images?.length ? product.images : [product.image]; const colors = product.colors?.length ? product.colors : [product.color]; const selectedColor = color || colors[0]; const variants = product.variants?.length ? product.variants : product.sizes.map(option => ({ id: `${product.id}-${option}`, color: product.color, size: option, price: product.price, stock: 8, sku: `${product.id}-${option}` })); const selected: ProductVariant | undefined = variants.find(variant => variant.color === selectedColor && variant.size === size); const price = selected?.price ?? product.price
  const addToCart = () => { if (!size) { alert('Please select a size'); return }; if (!selected || selected.stock < 1) { alert('This variant is out of stock'); return }; const line: CartLine = { productId: product.id, name: product.name, image: gallery[0], color: selectedColor, size, quantity, price, sku: selected.sku }; writeCart(addCartLine(readCart(), line)); alert('Added to bag') }
  const openWhatsApp = () => { if (!size) { alert('Please select a size'); return }; window.open(`https://wa.me/${process.env.NEXT_PUBLIC_WHATSAPP_NUMBER || '919999999999'}?text=${encodeURIComponent(whatsappText)}`, '_blank') }
  return <main className="detail-page"><header className="detail-header"><Link href="/#shop" className="back-link"><ArrowLeft size={16} /> BACK TO SHOP</Link><Link href="/" className="logo">LATTEY <span>WALLAH</span></Link><Link href="/checkout" className="product-cart-link" aria-label="Open cart"><ShoppingBag size={18} /></Link></header><div className="detail-grid"><div className="gallery"><div className="main-image"><img src={gallery[imageIndex]} alt={product.name} /><button className="gallery-arrow prev" onClick={() => setImageIndex((imageIndex + gallery.length - 1) % gallery.length)}><ArrowLeft size={17} /></button><button className="gallery-arrow next" onClick={() => setImageIndex((imageIndex + 1) % gallery.length)}><ArrowRight size={17} /></button></div><div className="thumbs">{gallery.map((image, index) => <button className={index === imageIndex ? 'selected' : ''} key={`${image}-${index}`} onClick={() => setImageIndex(index)}><img src={image} alt={`${product.name} view ${index + 1}`} /></button>)}</div></div><section className="product-info"><p className="eyebrow">{product.category.toUpperCase()} / lattey wala</p><h1>{product.name}</h1><div className="detail-price"><b>{money(price)}</b>{product.mrp > price && <del>{money(product.mrp)}</del>}</div><p className="detail-description">{product.description || 'Thoughtful everyday essentials, made with considered materials.'}</p><div className="option-block"><div className="option-label">COLOUR <b>{selectedColor}</b></div><div className="option-buttons">{colors.map(option => <button className={option === selectedColor ? 'active' : ''} key={option} onClick={() => { setColor(option); setSize('') }}>{option}</button>)}</div></div><div className="option-block"><div className="option-label">SIZE {size && <b>{size}</b>}</div><div className="option-buttons">{product.sizes.map(option => { const variant = variants.find(item => item.color === selectedColor && item.size === option); const soldOut = !variant || variant.stock === 0; return <button disabled={soldOut} className={`${option === size ? 'active' : ''} ${soldOut ? 'sold-out' : ''}`} key={option} onClick={() => setSize(option)}>{option}{soldOut && ' · OUT'}</button> })}</div></div><div className="quantity"><span>QUANTITY</span><div><button onClick={() => setQuantity(Math.max(1, quantity - 1))}><Minus size={14} /></button><b>{quantity}</b><button onClick={() => setQuantity(quantity + 1)}><Plus size={14} /></button></div></div><div className="detail-actions"><button className="button button-dark" onClick={addToCart}>ADD TO CART <ShoppingBag size={16} /></button><button className="button whatsapp" onClick={openWhatsApp}><MessageCircle size={17} /> ORDER ON WHATSAPP</button></div></section></div></main>
}
