'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import { ArrowLeft } from 'lucide-react'
import { arrayUnion, doc, getDoc, serverTimestamp, updateDoc } from 'firebase/firestore'
import { auth, db } from '@/lib/firebase'

const statuses = ['NEW', 'CONFIRMED', 'PREPARING', 'READY', 'OUT FOR DELIVERY', 'DELIVERED', 'CANCELLED', 'REJECTED']
type Order = { displayOrderId?: string; customer?: { name?: string; phone?: string; email?: string }; deliveryAddress?: { address?: string; city?: string; state?: string; pincode?: string; instructions?: string }; items?: Array<{ name?: string; color?: string; size?: string; sku?: string; quantity?: number; price?: number; total?: number }>; subtotal?: number; discount?: number; deliveryCharge?: number; totalAmount?: number; paymentStatus?: string; orderStatus?: string; razorpayOrderId?: string; razorpayPaymentId?: string }
const money = (value = 0) => `₹${value.toLocaleString('en-IN')}`
export default function AdminOrderDetail({ params }: { params: { orderId: string } }) {
  const [order, setOrder] = useState<Order | null>(null); const [status, setStatus] = useState(''); const [error, setError] = useState(''); const [ready, setReady] = useState(false)
  useEffect(() => { if (!auth) return; return auth.onAuthStateChanged(async user => { if (!user) { window.location.href = '/admin/login'; return }; try { const snapshot = await getDoc(doc(db, 'orders', params.orderId)); if (!snapshot.exists()) setError('Order not found'); else { const data = snapshot.data() as Order; setOrder(data); setStatus(data.orderStatus || 'NEW') } } catch { setError('Order details could not be loaded.') } finally { setReady(true) } }) }, [params.orderId])
  const saveStatus = async () => { if (!order || !status) return; const timestamp = new Date().toISOString(); await updateDoc(doc(db, 'orders', params.orderId), { orderStatus: status, updatedAt: serverTimestamp(), updatedBy: auth?.currentUser?.uid || '', statusHistory: arrayUnion({ status, timestamp }) }); setOrder({ ...order, orderStatus: status }) }
  if (!ready) return <main className="admin-page"><p>Loading order…</p></main>
  return <main className="admin-page"><header className="admin-header"><Link href="/admin/orders" className="back-link"><ArrowLeft size={16} /> ORDERS</Link><div className="logo">LATTEY <span>WALLAH</span></div><span className="eyebrow">ORDER DETAILS</span></header><section className="admin-content"><p className="eyebrow">ORDER #{order?.displayOrderId || params.orderId}</p>{error ? <p className="admin-error">{error}</p> : order && <div className="admin-order-detail"><section><h2>Customer & delivery</h2><p><b>{order.customer?.name}</b><br />{order.customer?.phone}<br />{order.customer?.email}</p><p>{order.deliveryAddress?.address}<br />{order.deliveryAddress?.city}, {order.deliveryAddress?.state} - {order.deliveryAddress?.pincode}</p>{order.deliveryAddress?.instructions && <p><b>Instructions:</b> {order.deliveryAddress.instructions}</p>}</section><section><h2>Items</h2>{order.items?.map((item, index) => <p className="admin-detail-line" key={`${item.sku}-${index}`}><span>{item.name}<br />{item.color} · {item.size} · SKU {item.sku} · Qty {item.quantity}</span><b>{money(item.total ?? (item.price || 0) * (item.quantity || 1))}</b></p>)}</section><section><h2>Payment</h2><p>Subtotal: <b>{money(order.subtotal)}</b><br />Discount: <b>{money(order.discount)}</b><br />Delivery: <b>{order.deliveryCharge ? money(order.deliveryCharge) : 'FREE'}</b><br />Total: <b>{money(order.totalAmount)}</b></p><p>Payment: <b>{order.paymentStatus}</b><br />Razorpay Order: {order.razorpayOrderId || '—'}<br />Payment ID: {order.razorpayPaymentId || '—'}</p></section><section><h2>Delivery status</h2><select value={status} onChange={event => setStatus(event.target.value)}>{statuses.map(value => <option key={value}>{value}</option>)}</select><button className="button button-dark" onClick={saveStatus}>SAVE STATUS</button></section></div>}</section></main>
}
